from __future__ import annotations

from pathlib import Path
import re
from typing import Any


YEAR_RE = re.compile(r"((?:19|20)\d{2})")
GENERIC_VALUES = {
    "",
    "adobe acrobat",
    "calibre",
    "generated by",
    "microsoft word",
    "scanner",
    "unknown",
    "untitled",
}


def _first_text(value: Any) -> str | None:
    if isinstance(value, dict):
        value = next(iter(value.values()), None)
    if isinstance(value, (list, tuple)):
        value = value[0] if value else None
    text = re.sub(r"\s+", " ", str(value or "")).strip()
    return text or None


def _is_untrusted(value: str, source_labels: set[str]) -> bool:
    normalized = value.strip().casefold()
    if normalized in GENERIC_VALUES:
        return True
    if normalized.startswith("@") or re.match(
        r"^(?:adobe acrobat|calibre|generated by|microsoft word|scanner)\b",
        normalized,
    ):
        return True
    if normalized in source_labels:
        return True
    if re.search(r"(?:https?://|www\.|archive\.org)", normalized):
        return True
    if re.search(r"[\\/].+\.(?:pdf|epub)$", normalized):
        return True
    return False


def _trusted(
    value: Any,
    source_labels: set[str],
) -> tuple[str | None, bool]:
    text = _first_text(value)
    if not text:
        return None, False
    if _is_untrusted(text, source_labels):
        return None, True
    return text, False


def read_pdf_metadata(
    path: Path,
    *,
    source_labels: list[str] | None = None,
) -> tuple[dict[str, str], list[str]]:
    """Read trustworthy PDF metadata without modifying the document."""
    labels = {
        str(label).strip().casefold()
        for label in (source_labels or [])
        if str(label).strip()
    }
    errors: list[str] = []
    try:
        from pypdf import PdfReader
    except ImportError:
        return {}, ["pypdf_not_installed"]

    try:
        reader = PdfReader(str(path))
    except Exception as exc:
        return {}, [f"pdf_read_failed:{type(exc).__name__}"]

    try:
        info = reader.metadata
    except Exception as exc:
        info = None
        errors.append(f"pdf_document_info_failed:{type(exc).__name__}")
    try:
        xmp = getattr(reader, "xmp_metadata", None)
    except Exception as exc:
        xmp = None
        errors.append(f"pdf_xmp_invalid:{type(exc).__name__}")
    title, title_ignored = _trusted(
        getattr(info, "title", None)
        or (info.get("/Title") if info else None),
        labels,
    )
    author, author_ignored = _trusted(
        getattr(info, "author", None)
        or (info.get("/Author") if info else None),
        labels,
    )
    if not title and xmp is not None:
        title, xmp_title_ignored = _trusted(
            getattr(xmp, "dc_title", None),
            labels,
        )
        title_ignored = title_ignored or xmp_title_ignored
    if not author and xmp is not None:
        author, xmp_author_ignored = _trusted(
            getattr(xmp, "dc_creator", None),
            labels,
        )
        author_ignored = author_ignored or xmp_author_ignored
    if title_ignored or author_ignored:
        errors.append("pdf_metadata_generic_ignored")

    date_value = _first_text(
        getattr(info, "creation_date", None)
        or (info.get("/CreationDate") if info else None)
        or (getattr(xmp, "xmp_create_date", None) if xmp else None)
    )
    year_match = YEAR_RE.search(date_value or "")
    values = {
        "title": title,
        "author": author,
        "year": year_match.group(1) if year_match else None,
    }
    return {
        key: value
        for key, value in values.items()
        if value
    }, errors
